//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet_Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ability()
        {
            this.PokemonAbilities = new HashSet<PokemonAbility>();
        }
    
        public long AbilityId { get; set; }
        public string Name { get; set; }
        public string Activation { get; set; }
        public string Limit { get; set; }
        public Nullable<long> KeywordId { get; set; }
        public string Effect { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonAbility> PokemonAbilities { get; set; }
    }
}
