//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet_Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Move()
        {
            this.PokemonMoves = new HashSet<PokemonMove>();
            this.TechnicalMedicines = new HashSet<TechnicalMedicine>();
        }
    
        public long MoveId { get; set; }
        public string Name { get; set; }
        public long TypeId { get; set; }
        public string Roll { get; set; }
        public long FrequencyId { get; set; }
        public string AccuracyCheck { get; set; }
        public long MoveStatId { get; set; }
        public string MoveRange { get; set; }
        public string Target { get; set; }
        public string Effect { get; set; }
        public string EffectScript { get; set; }
        public long ContestTypeId { get; set; }
        public string ContestRoll { get; set; }
        public string ContestKeyword { get; set; }
    
        public virtual ContestType ContestType { get; set; }
        public virtual Frequency Frequency { get; set; }
        public virtual MoveStat MoveStat { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonMove> PokemonMoves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TechnicalMedicine> TechnicalMedicines { get; set; }
    }
}
