//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet_Provider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Abilities { get; set; }
        public virtual DbSet<Capability> Capabilities { get; set; }
        public virtual DbSet<ContestType> ContestTypes { get; set; }
        public virtual DbSet<Frequency> Frequencies { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Move> Moves { get; set; }
        public virtual DbSet<MoveListType> MoveListTypes { get; set; }
        public virtual DbSet<MoveStat> MoveStats { get; set; }
        public virtual DbSet<Pokemon> Pokemons { get; set; }
        public virtual DbSet<TechnicalMedicine> TechnicalMedicines { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<TypeEffective> TypeEffectives { get; set; }
        public virtual DbSet<PokemonAbility> PokemonAbilities { get; set; }
        public virtual DbSet<PokemonMove> PokemonMoves { get; set; }
    }
}
