//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public long MoveId { get; set; }
        public string Name { get; set; }
        public string Roll { get; set; }
        public string AccuracyCheck { get; set; }
        public string MoveRange { get; set; }
        public string Target { get; set; }
        public string Effect { get; set; }
        public string EffectScript { get; set; }
        public string ContestRoll { get; set; }
        public string ContestKeyword { get; set; }
    
        public virtual ContestType ContestType { get; set; }
        public virtual Frequency Frequency { get; set; }
        public virtual MoveStat MoveStat { get; set; }
        public virtual Type Type { get; set; }
    }
}
