//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.PokemonAbility = new HashSet<PokemonAbility>();
            this.PokemonCapabilities = new HashSet<PokemonCapabilities>();
            this.PokemonMove = new HashSet<PokemonMove>();
        }
    
        public long PokemonId { get; set; }
        public string Name { get; set; }
        public long EntryId { get; set; }
        public long HP { get; set; }
        public long Attack { get; set; }
        public long Defense { get; set; }
        public long SpecialAttack { get; set; }
        public long SpecialDefense { get; set; }
        public long Speed { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public decimal MaleChance { get; set; }
        public decimal FemaleChance { get; set; }
        public long AvgHatchRate { get; set; }
        public string Diets { get; set; }
        public string Habitats { get; set; }
        public long Burrow { get; set; }
        public long Intelligence { get; set; }
        public long Jump { get; set; }
        public long Overland { get; set; }
        public long Power { get; set; }
        public long Sky { get; set; }
        public long Surface { get; set; }
        public long Underwater { get; set; }
        public long CaptureRate { get; set; }
        public long ExperienceDrop { get; set; }
        public string LevelUpScript { get; set; }
    
        public virtual Type Type { get; set; }
        public virtual Type Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonAbility> PokemonAbility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonCapabilities> PokemonCapabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonMove> PokemonMove { get; set; }
    }
}
