//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokemonMove
    {
        public long PokemonMoveId { get; set; }
        public long MoveId { get; set; }
        public long Level { get; set; }
    
        public virtual MoveListType MoveListType { get; set; }
        public virtual Pokemon Pokemon { get; set; }
    }
}
