//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PtaConnection : DbContext
    {
        public PtaConnection()
            : base("name=PtaConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Ability { get; set; }
        public virtual DbSet<Capability> Capability { get; set; }
        public virtual DbSet<ContestType> ContestType { get; set; }
        public virtual DbSet<Frequency> Frequency { get; set; }
        public virtual DbSet<Keyword> Keyword { get; set; }
        public virtual DbSet<Move> Move { get; set; }
        public virtual DbSet<MoveListType> MoveListType { get; set; }
        public virtual DbSet<MoveStat> MoveStat { get; set; }
        public virtual DbSet<Pokemon> Pokemon { get; set; }
        public virtual DbSet<PokemonAbility> PokemonAbility { get; set; }
        public virtual DbSet<PokemonCapabilities> PokemonCapabilities { get; set; }
        public virtual DbSet<PokemonMove> PokemonMove { get; set; }
        public virtual DbSet<TechnicalMedicine> TechnicalMedicine { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<TypeEffective> TypeEffective { get; set; }
    }
}
