//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSheet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalMedicine
    {
        public long TmRowId { get; set; }
        public string PtaId { get; set; }
        public long MoveId { get; set; }
        public double Price { get; set; }
    }
}
